"""Claim 4 — the catalog is generated, idempotent and reconciled.

Pure. `build()` turns contracts + the harvested estate + lineage + lifecycle + value detections into the
**desired catalog**, as Collibra Import API commands (resourceType / identifier / type / attributes /
relations / responsibilities — the documented shape). `diff()` compares the desired catalog with what the
catalog currently holds and returns only the commands that change something, so a second sync is empty.
`reconcile()` lists what exists in GCP but not in the catalog, what exists in the catalog but not in GCP,
and what exists in both with different attributes.

Every asset's identity is a stable external key derived from the BigQuery path — `<project>.<dataset>`,
`<project>.<dataset>.<table>`, `<project>.<dataset>.<table>.<column>` — so the same estate always maps
to the same assets. `Last Changed` is written only when an asset's content changes; when a run last
reconciled is a property of the run (the sync report), not of every asset, or a second run would
"change" every asset's timestamp.

Shapes follow the Collibra Import API guide (developer.collibra.com, read 2026-10-01 — docs/COLLIBRA.md):
a relation key is `<Source type>:<source role>:<target role>:<Target type>:<TARGET|SOURCE>`; a responsibility
names a role and a user group **by id**; ownership is declared on the **domain** (asset-level responsibilities
are off by default in Collibra Console and an import that sets them errors). The Import API cannot delete an
attribute by omitting it, so every asset of a type always carries the same attribute set — a value that no
longer applies is overwritten with an explicit "none", never left behind to be read as current.
"""

from __future__ import annotations

import json

from .contract import Contract
from .schema import harvest_columns

VOLATILE = frozenset({"Last Changed"})

# Steward's relation vocabulary, in the Import API's fully qualified form. The operating model the mock
# enforces (catalog/collibra.yaml) declares the same relations independently — a typo here is refused there.
IS_PART_OF_TABLE = "Column:is part of:contains:Table:TARGET"
IS_PART_OF_SCHEMA = "Table:is part of:contains:Schema:TARGET"
USES_COLUMN = "Report:uses:is used by:Column:TARGET"
REPRESENTED_BY = "Business Term:is represented by:represents:Report:TARGET"


def _ident(name: str, domain: str, community: str) -> dict:
    return {"name": name, "domain": {"name": domain, "community": {"name": community}}}


def _asset(name, domain, community, typ, status, attributes, relations=None, display=None) -> dict:
    cmd = {
        "resourceType": "Asset",
        "identifier": _ident(name, domain, community),
        "type": {"name": typ},
        "status": {"name": status},
        "displayName": display or name.rsplit(".", 1)[-1],
        "attributes": {k: [{"value": str(v)}] for k, v in sorted(attributes.items())},
    }
    if relations:
        cmd["relations"] = {k: sorted(v, key=lambda t: t["name"]) for k, v in sorted(relations.items())}
    return cmd


def _responsibilities(c: Contract, group_ids: dict[str, str]) -> dict:
    """Role -> user group **id** (the Import API names groups by id). A group with no id is an error, not a
    guess: no default owner (doctrine 3)."""
    out = {}
    for role, group in (("Owner", c.owner), ("Steward", c.steward), ("Custodian", c.custodian)):
        if group not in group_ids:
            raise ValueError(f"{c.dataset}: {role} {group!r} has no user group id in the catalog directory")
        out[role] = [{"userGroup": {"id": group_ids[group]}}]
    return out


def physical_domain(dataset: str) -> str:
    return f"{dataset} (BigQuery)"


GLOSSARY, REPORTS = "Business Glossary", "Dashboards (Looker)"


def build(
    contracts: list[Contract],
    harvest: dict,
    project: str,
    community: str,
    lineage_detail: dict | None = None,
    lifecycle: list[dict] | None = None,
    glossary: dict[str, dict] | None = None,  # term -> {"definitions": [...], "dashboards": [...]}
    legacy_detections: dict[str, list[str]] | None = None,
    waivers: list[dict] | None = None,
    group_ids: dict[str, str] | None = None,
    mode: str = "MOCK",
) -> list[dict]:
    """The desired catalog, as Import API commands, in dependency order (community, domains, assets).
    `mode` (MOCK | REAL) is written into the community and every domain description, so the catalog says
    where it was generated for (doctrine 2)."""
    group_ids = group_ids or {}
    generated = f"Generated by Steward from the data contracts and the harvested BigQuery estate (catalog mode: {mode}). Edits made here are reverted by the next sync."
    by_ds = {c.dataset: c for c in contracts}
    cols = harvest_columns(harvest)
    datasets = sorted({t.split(".")[0] for t in harvest} | set(by_ds))
    cmds: list[dict] = [{"resourceType": "Community", "identifier": {"name": community}, "description": generated}]
    for ds in datasets:
        dcmd = {
            "resourceType": "Domain",
            "identifier": {"name": physical_domain(ds), "community": {"name": community}},
            "type": {"name": "Physical Data Dictionary"},
            "description": generated,
        }
        if ds in by_ds:  # an uncontracted dataset has no owner to name; the gate reports it, the catalog invents none
            dcmd["responsibilities"] = _responsibilities(by_ds[ds], group_ids)
        cmds.append(dcmd)
    for name, typ in ((GLOSSARY, "Glossary"), (REPORTS, "BI Catalog")):
        cmds.append(
            {
                "resourceType": "Domain",
                "identifier": {"name": name, "community": {"name": community}},
                "type": {"name": typ},
                "description": generated,
            }
        )

    waiver_of = {w["target"]: w for w in waivers or []}
    for ds in datasets:
        c = by_ds.get(ds)
        dom = physical_domain(ds)
        schema = f"{project}.{ds}"
        if c:
            cmds.append(
                _asset(
                    schema,
                    dom,
                    community,
                    "Schema",
                    "Accepted",
                    {
                        "Description": c.description,
                        "Lawful Basis": c.lawful_basis,
                        "Retention Period": f"{c.retention.period_days} days",
                        "Retention Legal Basis": c.retention.legal_basis,
                        "Contract Version": c.version,
                    },
                    display=ds,
                )
            )
        else:
            w = next((w for t, w in waiver_of.items() if t.startswith(ds + ".")), None)
            note = f"waived by {w['id']} until {w['expires']}" if w else "no waiver — build red"
            cmds.append(
                _asset(
                    schema,
                    dom,
                    community,
                    "Schema",
                    "Candidate",
                    {
                        "Description": f"No contract ({note}). Every column held at `restricted`; proposals below await an owner.",
                        "Lawful Basis": "NOT DECLARED",
                        "Retention Period": "NOT DECLARED",
                        "Retention Legal Basis": "NOT DECLARED",
                        "Contract Version": "none",
                    },
                    display=ds,
                )
            )
        tables = sorted(
            {t.split(".", 1)[1] for t in harvest if t.startswith(ds + ".")} | (set(c.tables) if c else set())
        )
        for t in tables:
            fq = f"{ds}.{t}"
            tbl = c.tables.get(t) if c else None
            tname = f"{project}.{fq}"
            cmds.append(
                _asset(
                    tname,
                    dom,
                    community,
                    "Table",
                    "Accepted" if tbl else "Candidate",
                    {
                        "Description": tbl.description if tbl else "Undeclared: no contract describes this table.",
                        "Contract Version": c.version if c and tbl else "none",
                    },
                    relations={IS_PART_OF_SCHEMA: [_ident(schema, dom, community)]},
                    display=t,
                )
            )
            paths = sorted(set(cols.get(fq, {})) | (set(tbl.columns) if tbl else set()))
            for path in paths:
                col = tbl.columns.get(path) if tbl else None
                info = cols.get(fq, {}).get(path)
                if col is not None:
                    attrs = {
                        "Description": col.description,
                        "Personal Data Classification": col.classification.value,
                        "Personal Data Kinds": ", ".join(col.kinds) or "none",
                        "Masking": json.dumps({r: m.value for r, m in sorted(col.masking.items())})
                        if col.masking
                        else "none (untagged)",
                        "Technical Data Type": col.type,
                        # overwritten, never omitted: the Import API cannot delete an attribute by leaving it out
                        "Proposed Classification": "none (declared by a contract)",
                        "Proposed Description": "none (declared by a contract)",
                    }
                    status = "Accepted"
                else:
                    proposed = (legacy_detections or {}).get(f"{fq}.{path}", [])
                    attrs = {
                        "Description": "Undeclared column: held at `restricted` (doctrine 1) until a contract declares it.",
                        "Personal Data Classification": "restricted (no contract)",
                        "Personal Data Kinds": "unknown (no contract)",
                        "Masking": "restricted: denied to every role (no contract)",
                        "Technical Data Type": info.type if info else "unknown",
                        "Proposed Classification": "personal" if proposed else "unknown — needs an owner's review",
                        "Proposed Description": f"Values look like: {', '.join(proposed)}"
                        if proposed
                        else "No personal data found by value in the scan.",
                    }
                    status = "Candidate"
                cmds.append(
                    _asset(
                        f"{tname}.{path}",
                        dom,
                        community,
                        "Column",
                        status,
                        attrs,
                        relations={IS_PART_OF_TABLE: [_ident(tname, dom, community)]},
                        display=path,
                    )
                )

    states = {d["dashboard"]: d for d in lifecycle or []}
    for did, rows in sorted((lineage_detail or {}).get("dashboards", {}).items()):
        used = sorted({col for r in rows for col in r["columns"] if not col.endswith(".*")})
        st = states.get(did, {})
        cmds.append(
            _asset(
                f"looker:{did}",
                REPORTS,
                community,
                "Report",
                "Accepted",
                {
                    "Description": f"Looker dashboard {did} (LookML).",
                    "Lifecycle State": st.get("state", "unknown — no usage export"),
                },
                relations={
                    USES_COLUMN: [
                        _ident(f"{project}.{c_}", physical_domain(c_.split(".")[0]), community) for c_ in used
                    ]
                },
                display=did,
            )
        )
    for term, g in sorted((glossary or {}).items()):
        defs = sorted(set(g["definitions"]))
        conflict = len(defs) > 1
        definition = ("CONFLICT — " if conflict else "") + " | ".join(defs)
        dashboards = sorted(d for d in g.get("dashboards", []) if d in (lineage_detail or {}).get("dashboards", {}))
        cmds.append(
            _asset(
                term,
                GLOSSARY,
                community,
                "Business Term",
                "Under Review" if conflict else "Accepted",
                {"Definition": definition},
                relations={REPRESENTED_BY: [_ident(f"looker:{d}", REPORTS, community) for d in dashboards]},
            )
        )
    return cmds


def key(cmd: dict) -> tuple:
    i = cmd["identifier"]
    if cmd["resourceType"] == "Asset":
        return ("Asset", i["domain"]["community"]["name"], i["domain"]["name"], i["name"])
    if cmd["resourceType"] == "Domain":
        return ("Domain", i["community"]["name"], i["name"])
    return ("Community", i["name"])


def _comparable(cmd: dict) -> dict:
    c = dict(cmd)
    if "attributes" in c:
        c["attributes"] = {k: v for k, v in c["attributes"].items() if k not in VOLATILE}
    return c


def diff(desired: list[dict], current: dict[tuple, dict], at: str) -> list[dict]:
    """Commands that create or change something. `current` = {key: command as last written}. `at` stamps
    `Last Changed` on changed assets only."""
    out = []
    for cmd in desired:
        if _comparable(current.get(key(cmd), {})) == _comparable(cmd):
            continue
        if cmd["resourceType"] == "Asset":
            cmd = {**cmd, "attributes": {**cmd["attributes"], "Last Changed": [{"value": at}]}}
        out.append(cmd)
    return out


def reconcile(
    harvest: dict,
    current: dict[tuple, dict],
    desired: list[dict],
    project: str,
    pending_first_write: frozenset[str] = frozenset(),
) -> dict:
    """Four lists, by stable key. The first three are the ones the catalog owes GCP: in GCP and not in the
    catalog · in the catalog and not in GCP · in both, differing. The fourth is what Steward generates that is
    not a GCP object (domains, dashboards, glossary terms) and the catalog lacks.

    `pending_first_write` = datasets a contract declares whose tables are created by a log sink on its first
    write (DECISIONS B15): the dataset is catalogued, GCP will have it once the sink writes, and until then it
    is listed under its own heading instead of being hidden or counted as drift.

    "Differing" compares the whole command — attributes, status, relations, responsibilities — so a hand-edited
    owner shows up, not only a hand-edited description."""
    cols = harvest_columns(harvest)
    datasets = {t.split(".")[0] for t in harvest}
    estate = (
        {f"{project}.{d}" for d in datasets}
        | {f"{project}.{t}" for t in harvest}
        | {f"{project}.{t}.{p}" for t, cs in cols.items() for p in cs}
    )
    physical = ("Schema", "Table", "Column")
    cat = {k[3]: v for k, v in current.items() if k[0] == "Asset" and v["type"]["name"] in physical}
    differing = []
    for k_, d in sorted((key(c), c) for c in desired):
        have = current.get(k_)
        if have is None:
            continue  # absent from the catalog: listed above, not "differing"
        a, b = _comparable(have), _comparable(d)
        changed = []
        for fld in sorted(set(a) | set(b)):
            if fld == "attributes":
                changed += [
                    f"attribute:{x}"
                    for x in sorted(set(a.get(fld, {})) | set(b.get(fld, {})))
                    if a.get(fld, {}).get(x) != b.get(fld, {}).get(x)
                ]
            elif a.get(fld) != b.get(fld):
                changed.append(fld)
        if changed:
            differing.append(
                {"resource": " / ".join(k_[1:]) if k_[0] != "Community" else k_[1], "type": k_[0], "differs": changed}
            )
    generated = [c for c in desired if not (c["resourceType"] == "Asset" and c["type"]["name"] in physical)]
    return {
        "in_gcp_not_in_catalog": sorted(estate - set(cat)),
        "in_catalog_not_in_gcp": sorted(set(cat) - estate - {f"{project}.{d}" for d in pending_first_write}),
        "pending_first_write": sorted(f"{project}.{d}" for d in pending_first_write if f"{project}.{d}" in cat),
        "in_both_differing": differing,
        "generated_not_in_catalog": sorted(" / ".join(key(c)[1:]) for c in generated if key(c) not in current),
    }
