"""Claim 6 (compiled side): approved, unexpired grants → IAM bindings with an expiry condition; listable
datasets → Analytics Hub listings; BigQuery Data Access audit logs → a sink into BigQuery.

Deterministic: which grants are live is decided against the ledger's own `as_of`, never a clock.
"""

from __future__ import annotations

import json
import re

from .contract import Contract
from .marketplace import Outcome, condition_expression


def _ident(s: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", s.lower())


def compile_marketplace(contracts: list[Contract], active: list[Outcome]) -> dict:
    by_ds = {c.dataset: c for c in contracts}
    R: dict = {}
    grants = {}
    for o in sorted(active, key=lambda o: o.request["id"]):
        req, dec = o.request, o.decision
        grants[_ident(req["id"])] = {
            "dataset_id": req["dataset"],
            "role": "roles/bigquery.dataViewer",
            "member": f'${{var.grantees["{o.member}"]}}',
            "condition": {
                "title": f"steward-{req['id']}"[:100],
                "description": f"{req['id']}: {req['requester']} as {req['seat']}, approved by {dec['by']} at {dec['at']}; expires {o.expires_at}",
                "expression": condition_expression(o.expires_at),
            },
        }
    if grants:
        R["google_bigquery_dataset_iam_member"] = grants

    R["google_bigquery_analytics_hub_data_exchange"] = {
        "marketplace": {
            "data_exchange_id": "steward_marketplace",
            "display_name": "Halverra data marketplace",
            "description": "Datasets listed by their contracts. Access is requested, approved by a named owner, and expires.",
            "location": "${lower(var.location)}",
        }
    }
    listings = {}
    for c in sorted(contracts, key=lambda c: c.dataset):
        if not c.marketplace.listable:
            continue
        listings[c.dataset] = {
            "location": "${lower(var.location)}",
            "data_exchange_id": "${google_bigquery_analytics_hub_data_exchange.marketplace.data_exchange_id}",
            "listing_id": f"steward_{c.dataset}",
            "display_name": c.dataset,
            "description": f"{c.description} Grantable to {', '.join(c.marketplace.grantable_roles)} for at most {c.marketplace.max_grant_days} days; approved by {c.marketplace.approvers}.",
            "request_access": "mailto:" + c.marketplace.approvers.split(":", 1)[1],
            "bigquery_dataset": {"dataset": f"projects/${{var.project_id}}/datasets/{c.dataset}"},
        }
    if listings:
        R["google_bigquery_analytics_hub_listing"] = listings

    # Who read what: BigQuery Data Access audit logs into the dataset whose contract declares the sink (B15).
    sink_ds = [c for c in contracts if c.log_sink]
    audit = sink_ds[0].dataset if len(sink_ds) == 1 else None  # validate reports LOG_SINK_DUPLICATE / none
    if audit:
        R["google_logging_project_sink"] = {
            "data_access": {
                "name": "steward-data-access",
                "destination": f"bigquery.googleapis.com/projects/${{var.project_id}}/datasets/{audit}",
                "filter": 'logName:"cloudaudit.googleapis.com%2Fdata_access" AND protoPayload.serviceName="bigquery.googleapis.com"',
                "unique_writer_identity": True,
                "bigquery_options": {"use_partitioned_tables": True},
            }
        }
        R["google_bigquery_dataset_iam_member"] = {
            **R.get("google_bigquery_dataset_iam_member", {}),
            "audit_sink_writer": {
                "dataset_id": audit,
                "role": "roles/bigquery.dataEditor",
                "member": "${google_logging_project_sink.data_access.writer_identity}",
            },
        }
    seats = sorted({o.member for o in active})
    doc = {
        "//": "Generated by steward (src/steward/core/compile_marketplace.py) from marketplace/ledger.yaml and contracts/.",
        "resource": R,
        "variable": {
            "grantees": {
                "description": "Requester -> the single IAM member that person reads as (user: or serviceAccount:, never a group: a grant goes to one person, not a seat). Distinct from the governance layer's `principals`, which maps seats.",
                "type": "map(string)",
                "validation": [
                    {
                        "condition": "${alltrue([for k in "
                        + json.dumps(seats)
                        + " : contains(keys(var.grantees), k)])}",
                        "error_message": "grantees must bind every person holding a live grant: "
                        + (", ".join(seats) or "(none)")
                        + ".",
                    },
                    {
                        "condition": '${alltrue([for v in values(var.grantees) : can(regex("^(user|serviceAccount):", v))])}',
                        "error_message": "a grantee is one person (user:) or the account standing in for them (serviceAccount:), never a group.",
                    },
                ],
            }
        },
    }
    unknown = sorted({o.request["dataset"] for o in active} - set(by_ds))
    if unknown:
        raise ValueError(f"grants on datasets with no contract: {unknown}")

    def _sorted(d):
        if isinstance(d, dict):
            return {k: _sorted(d[k]) for k in sorted(d)}
        if isinstance(d, list):
            return [_sorted(x) for x in d]
        return d

    return {"infra/marketplace/generated.tf.json": _sorted(doc)}
