"""Identities for the demo estate: one service account per seat and per requester, so the three-role
transcripts (claim 2) and the expiring grant (claim 6) need no human account and no key.

A seat is a role in the contracts (`analyst@GR`, `bi_service`, a contract's steward group...). The compiled
IAM binds seats to members through `var.principals`; here each seat becomes `serviceAccount:<id>@<project>`.
The deployer impersonates them (roles/iam.serviceAccountTokenCreator, bootstrap) to run one query as each.

Deterministic and collision-checked: two seats that would share an account id are an error, never a merge.
"""

from __future__ import annotations

import re

from .contract import Contract, Roles
from .marketplace import Outcome

ACCOUNT_ID = re.compile(r"^[a-z][a-z0-9-]{4,28}[a-z0-9]$")


def account_id(seat: str) -> str:
    """`analyst@GR` -> seat-analyst-gr · `group:crm-stewards@x` -> seat-crm-stewards · `user:a.b@x` -> person-a-b."""
    if seat.startswith("user:"):
        prefix, name = "person", seat.split(":", 1)[1].split("@", 1)[0]
    elif seat.startswith(("group:", "serviceAccount:")):
        prefix, name = "seat", seat.split(":", 1)[1].split("@", 1)[0]
    else:
        prefix, name = "seat", seat
    ident = f"{prefix}-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    if not ACCOUNT_ID.match(ident):
        raise ValueError(f"{seat!r} gives the service-account id {ident!r}, which GCP refuses (6-30 chars, a-z 0-9 -)")
    return ident


def contract_seats(contracts: list[Contract], roles: Roles) -> list[str]:
    from .compile import seats_for

    return sorted({seat for c in contracts for role in roles.roles for seat in seats_for(roles, role, c)})


def compile_seats(contracts: list[Contract], roles: Roles, active: list[Outcome]) -> dict[str, dict]:
    seats = contract_seats(contracts, roles)
    people = sorted({o.member for o in active})
    mapping: dict[str, str] = {}
    for who in [*seats, *people]:
        mapping[who] = account_id(who)
    clash = {a for a in mapping.values() if list(mapping.values()).count(a) > 1}
    if clash:
        raise ValueError(f"seats share a service-account id: {sorted(clash)}")

    accounts = {}
    for who, aid in sorted(mapping.items(), key=lambda kv: kv[1]):
        accounts[aid.replace("-", "_")] = {
            "account_id": aid,
            "display_name": f"Steward demo identity: {who}",
            "description": f"Stands in for {who} so the demo needs no human account and no key. Created by steward from contracts/.",
        }
    doc = {
        "//": "Generated by steward (src/steward/core/compile_seats.py) from contracts/ and marketplace/ledger.yaml. Edit those, then `make generate`.",
        "resource": {"google_service_account": accounts},
    }
    return {
        "infra/estate/identities.tf.json": doc,
        "infra/seats.json": {
            "//": "Seat or requester -> service-account id. scripts/tfvars.py turns it into var.principals / var.grantees for a project.",
            "seats": {w: mapping[w] for w in seats},
            "people": {w: mapping[w] for w in people},
        },
    }
